export const KEYVAL_KEYS = {
    APP_STATE: 'APP_STATE',
    CHATLIST_TREEVIEW_STATE: 'CHATLIST_TREEVIEW_STATE',

    THEME_SETTINGS_STORE_KEY: 'THEME_SETTINGS_STORE_KEY',
    OPEN_AI_SETTINGS_STORE_KEY: 'OPEN_AI_SETTINGS_STORE_KEY',
    ANTHROPIC_SETTINGS_STORE_KEY: 'ANTHROPIC_SETTINGS_STORE_KEY',
    CHAT_SETTINGS_KEY: 'CHAT_SETTINGS_KEY',
    AZURE_SETTINGS_STORE_KEY: 'AZURE_SETTINGS_STORE_KEY',
}