export const KEYVAL_KEYS = {
    USER_SETTINGS: 'USER_SETTINGS',
    APP_STATE: 'APP_STATE',
    CHATLIST_TREEVIEW_STATE: 'CHATLIST_TREEVIEW_STATE',
    THEME_STORE: 'THEME_STORE',
    OPEN_AI_SETTINGS_STORE_KEY: 'OPEN_AI_SETTINGS_STORE_KEY',
    AZURE_SETTINGS_STORE_KEY: 'AZURE_SETTINGS_STORE_KEY',
}